# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Joint_1:
    has_velocity_limits: true
    max_velocity: 0.261799383
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_2:
    has_velocity_limits: true
    max_velocity: 0.261799383
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_3:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  Joint_4:
    has_velocity_limits: true
    max_velocity: 0.261799383
    has_acceleration_limits: false
    max_acceleration: 0